# Generated by Django 2.2.6 on 2019-10-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letitbeeasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.FileField(default='abcd/', upload_to='1/'),
        ),
    ]
